version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=sqlite:///./analysis.db
      - FRONTEND_URL=http://frontend:5173
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app

  # Optional: Prometheus configuration
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      # Create a prometheus directory if it doesn't exist
      - ./prometheus:/etc/prometheus
    # Remove the specific file mapping
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge